movement:
  allow-move: false
password:
  min-length: 4
  max-length: 20
auto:
  login: true
session:
  single: true
allow:
  commands:
  - login
  - register
  - help
data:
  language: eng
  old: false